### ISSUE TITLE
Set does not seem to overwrite existing cache entry

### ISSUE THREAD

**Issue by gcleaves** [PHPSocialNetwork/phpfastcache#102]
Is it necessary to explicitly delete an entry before setting it in order to update it? 

```
$cache->set("key",1,$one_hour);
$cache->set("key",5,$one_hour);
```
$cache->get("key") returns 1 instead of 5, not what I expected.

**Comment by khoaofgod** [comment]
which driver Files, SQLte ? or Memcache @gcleaves

**Comment by gcleaves** [comment]
Files.  Linux OS.  I will try to get you more detailed information....

**Comment by juntao** [comment]
I had the same issue. And I believe the problem is this line:

https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Drivers/files.php#L130

It will NOT write if the cache file already exists ... (because the last file_exists check)

Also, the $written variable should start off "false" on this line:

https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Drivers/files.php#L124

**Comment by khoaofgod** [comment]
K, I will take it this weekend

**Comment by khoaofgod** [comment]
Fixed

**Comment by juntao** [comment]
Thanks! I tried the new release and it works flawlessly now. 
CheersMichael






On Sat, Feb 20, 2016 at 6:59 PM -0800, "Khoa Bui" <notifications@github.com> wrote:












Fixed
