### ISSUE TITLE
Memcached and Redis's LRU algorithm

### ISSUE THREAD

**Issue by atn4z7** [PHPSocialNetwork/phpfastcache#236]
Hi,
If the storage mode is set to Memcached or Redis, will LRU be used by default and no configuration is needed? Also, is there a way I can set the max memory for either Memcached or Redis via phpfastcache interface (100MB for example)? 
Thanks in advance!

**Comment by khoaofgod** [comment]
hi An,
by default it will connect to default setting of Memcache & Redis.
If your server have custom setup, you can look at phpFastCache folder Examples for redis & memcache.
We can't set limit max memory for both of them, because they control over Background Service. but you can limit by the deamon command on memcache, or redis config on server.
