### ISSUE TITLE
Store an object with phpfastcache

### ISSUE THREAD

**Issue by sv1gzf** [PHPSocialNetwork/phpfastcache#263]
Is it possible to use phpastcache to store an object without serialization??? 
I made some tests with serialization and memcache but the serialization - userialization takes long time :(

**Comment by khoaofgod** [comment]
for File Mode - You can't write object without serialization .
for Memcached - Objects doesn't need serialization to write. phpFastCache don't do serialization for any type of Memory Caching like Memcached / Predis / etc ...

**Comment by koenpunt** [comment]
@sv1gzf have a look at igbinary

> Igbinary is a drop in replacement for the standard php serializer. Instead of
time and space consuming textual representation, igbinary stores php data
structures in a compact binary form. Savings are significant when using
memcached or similar memory based storages for serialized data.
http://pecl.php.net/package/igbinary

**Comment by khoaofgod** [comment]
@sv1gzf you are using memcache right ? phpFastCache doesn't do serialization on Memcache. It just pass the whole object / varible to Memcache, and let memcache handle it. The serialization is only happen for Files Cache.

**Comment by Geolim4** [comment]
serialization is a standart of php included in the core and fast enough for common uses.
We should not rely to third party libs due to performances issues.
Even if pecl extension are compiled they're still less efficient that php core functions :)

**Comment by koenpunt** [comment]
> Even if pecl extension are compiled they're still less efficient that php core functions :)

This simply isn't true. Compiled C libraries and/or extensions operate at the same level as the php functions. For example, Igbinary serialize/unserialize functions are even faster than the "core" php serialize/unserialize functions. The only downside to it is that the serialized data isn't humanly readable anymore.

**Comment by koenpunt** [comment]
And I don't say this library should depend on it, but I'm just suggesting it to @sv1gzf for his implementation.

**Comment by khoaofgod** [comment]
For Files Cache:
by default serialize is slower than json_encode around 30% as my benmark. But then some people want to cache an object, and json_encode / decode can't handle it good. So, I picked serialize for Files_Cache. the igBinary does serialize faster as binary, but then user will have to install it on their server. 
By default PHP 6 & 7, make serialize / core faster than json_encode 70% ( that what they said on their site ).

I think I should make a config for people choose json_encode, serialize, or even put a custom serialize/unserialize for their Files Cache. I will like that, because for my project, I feel like json_encode is enought for me, and some of my type caching, I don't even need serialize.

**Comment by Geolim4** [comment]
The problem is that json_encode doesn't offers any **integrity control**. This part is very important since the cache must be 100% trusted. (Speaking about integrity)
Also serialize is not less readable than json_encode (unless if you use the JSON_PRETTY_PRINT which use significant more disk space).

**Comment by Geolim4** [comment]
And i forgot: You can't save object name/state with json_encode() :'(

**Comment by khoaofgod** [comment]
oh, just forget it, I will just keep serialize as default for file cache driver.
Other drivers like: memcached, predis, mongodb, wincache ...etc <-- phpFastCache just pass the whole object to the driver, and I don't think they do any serialize methods there for sure, because they store in memory.

**Comment by koenpunt** [comment]
> just pass the whole object to the driver

Even though you pass the object, internally all these objects are serialized into something that can be represented in the storage of the driver.

**Comment by khoaofgod** [comment]
@koenpunt then what can we do ? If memcached decided to do serialized somehow, then it's up to  them. hahahahahahah. 

There are 4 things involved in fetching a remote object whether you fetch from memcached / redis / or database: 
-serialization/deserialization
-network transfer
-request processing and 
-potential disk access

The question here is the original poster asked: Is it possible to use phpastcache to store an object without serialization? 

and he tested with memcached. 

The answer is: phpFastCache only do serialization for File Cache. For other drivers, phpFastCache don't do serialization, and just pass the whole object to that driver. Also, I don't really know why he did serialization before set object into memcached, that just make serialization x 2 times: Once himself, and Once again by Memcached or the driver.

**Comment by koenpunt** [comment]
@khoaofgod I'm just providing other solutions, instead of just saying no.

And the problem possibly lies here, [phpFastCache/Core/DriverInterface.php#L38](https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Core/DriverInterface.php#L38), what makes @sv1gzf think only strings are supported.

**Comment by khoaofgod** [comment]
hahaha, true. I will make a note to update that line.

**Comment by koenpunt** [comment]
>  unless if you use the JSON_PRETTY_PRINT which use significant more disk space

_significant_ isn't the right word here, test for example the following:

```
$ php -r 'echo json_encode($_SERVER);' > compressed.json
$ php -r 'echo json_encode($_SERVER, JSON_PRETTY_PRINT);' > pretty.json
$ stat -f "%z %N" *.json
2023 compressed.json
2302 pretty.json
```

Which is only 13% difference.

**Comment by Geolim4** [comment]
For small objects yes, it's small, what about big object ? :)
