### ISSUE TITLE
V5 on php 5.3

### ISSUE THREAD

**Issue by reno1979** [PHPSocialNetwork/phpfastcache#298]
I  know the requirements are php 5.5 or higher. 

But I was wondering what  parts of the code causes this requirement. 

I noticed the sleek array creation with  the [ ]   
Is there a lot more that causes php 5.5 requirements?

**Comment by Geolim4** [comment]
Hi Reno,

The sleek array (5.4) is not the only one reason that lead us to make this choice.
The main reason is that php 5.3 and 5.4 are now in EOL state which mean they are **abandonned**, the 5.5 is also so close of EOL because it reached the Security Fixe Only state. By this choice we want to push the users to migrate as soon of possible to a more recent php version. It may look selfish, but we can't support these old boys forever.

The other reason is the full support of array and string literal dereferencing (5.5) and also the class member access on instantiation (5.4).

Finally, starting php 5.5, each major versions gain a lot of performances improvement regarding specific criteria such array iteration, objects storage/manipulation etc.

Regards,
Georges

**Comment by reno1979** [comment]
Hello Georges, 

;) I can understand that the sleek array [ ] is not the only reason to switch to 5.5
I also agree that users should be encouraged to migrate as soon as possible. 

In my current projects I still have very old parts of code and a migration tot 5.6 or higher is not yet available for each of the projects.

Because of the completely rewritten code in v5 (and that I rather use the new products), the interfaces we have build with the phpfastcacheengine must also be able to communicate with v4. 
This way we can support php 5.3 using v4 of phpfastcache.  

If v5 did not use a lot of new techniques, I was considering a 'hackish' (how do you spell that) solution by rewriting some code in v5. 

Of course where are trying to get the upgrade to > 5.6 done as soon of possible :)

**Comment by Geolim4** [comment]
If you code is very old old you can still use the v4 for 2 years until we stop the support of this one.
