### ISSUE TITLE
Manual cache file deletion?

### ISSUE THREAD

**Issue by Jakobud** [PHPSocialNetwork/phpfastcache#35]
I just started messing around with this.  Works great so far.  I was wondering if it's possible to manually delete cache files when you are using filesystem storage as the caching type?  I don't see where the cache files are stored on the file system.

There are some cases where I need to manually delete the cache and let my webpage rebuild the cache because a DB query was modified and I can't wait until the cache expires.  Is the only way to delete the cache to call `$cache->delete()`?

**Comment by fajarfariyanton** [comment]
how to save all cache to one folder , and not create one folder to one cache

**Comment by khoaofgod** [comment]
set the storage to "sqlite" , it will save to sqlite 1 - 2 files only.

Because Linux / Windows directory only allow around 30,000 files I think.

So, if you don't split them to multiple folder, the cache folder will dead after couple weeks, and also it's very diffucuti to clean up a folder have more than 10,000 files, slow and cost memory when reading everything from that folder. In real world, 1 folder contant all cache files is bad. Use "sqlite" / "memcached" / "memcache" if you don't want to deal with files.

I suggest sqlite
