### ISSUE TITLE
How to use correctly expiresAt()

### ISSUE THREAD

**Issue by fastdriven** [PHPSocialNetwork/phpfastcache#360]
I want create a cache for every week
for example:  from Tuesday to Tuesday
I Suppose for realise this, I should use the method: expireAt(as a DateTimeInterface object)

but I can't do it
do you help me please with an exemple?
I did not find with this method on internet.

> $config = array("storage" => "files", "path" => "app/cache/");
CacheManager::setDefaultConfig($config);
$InstanceCache = CacheManager::getInstance('files');
$CachedString = $InstanceCache->getItem('dataForWeek');
if (is_null($CachedString->get())) {
      $CachedString->set($data)->expiresAt(??????????);
      $InstanceCache->save($CachedString);
}

**Comment by Geolim4** [comment]
Hello,

Did you read the wiki and the readme ?
I guess not :)

Use expireAfter() to use DateInterval object. Else DateTime or Int fpr
ExpireAt()

Cheers :)
Georges

Le 12 sept. 2016 1:27 PM, "fastdriven" <notifications@github.com> a écrit :

I want create a cache for every week
for example: from Tuesday to Tuesday
I Suppose for realise this, I should use the method: expireAt(as a
DateTimeInterface object)

but I can't do it
do you help me please with an exemple?
I did not find with this method on internet.

$config = array("storage" => "files", "path" => "app/cache/");
CacheManager::setDefaultConfig($config);
$InstanceCache = CacheManager::getInstance('files');
$CachedString = $InstanceCache->getItem('dataForWeek');
if (is_null($CachedString->get())) {
$CachedString->set($data)->expiresAt(??????????);
$InstanceCache->save($CachedString);
}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PHPSocialNetwork/phpfastcache/issues/360>, or mute the
thread
