### ISSUE TITLE
Files driver, simultaneous write

### ISSUE THREAD

**Issue by brainfoolong** [PHPSocialNetwork/phpfastcache#365]
Hi, i today found this library and it looks really great to me. But the thing is, does the "files" driver also can handle multiple "write" calls from different sources at the same time? I mean, i've seen so many caching libraries that always have the problem When i use a file based cache than it sometimes comes to "Access denied" because some other thread accessing the same file at the same time for write access.

I quick look at the driver for the files, i cannot find any blocking mechanism like `flock` or so that will try to prevent exactly that problem.

The weird thing is, i don't found any related problem to this, so, does this problem not happen with phpfastcache? Can i safely use files cache with heavy load servers that also do much write actions on it?

Even native SQLite cannot handle such situations.

I just want to ask before i change my code to use phpfastcache.

**Comment by Geolim4** [comment]
Hello Roland,

This is a very pertinent observation that you raised !
PhpFastCache is not really immunized against multiple write calls, because an option allow you to choose the "path" where the lib will write the files. The path allow multiple "write calls" under a circumstance where for a specific http request you need to write cache on disk with two different instances.

In the case of parallel http requests which use the same cache path i never encountered the case probably because our tests write a small amount of serialized data which are too fast to write on disk to notice any blocking issue.

Anyway this problem concern only files-based drivers such as Files, Sqlite, etc. You can safely use memory-based driver such as Redis, Ssdb and other big boys, they have internal mechanism that prevent this kind of problem.

I will made some tests on my side to make sure that we are not concerned by this issue, if we are i will made a hotfix quickly.

On your side you can start migrating your code to Pfc and if the problem occurs you can get in touch with me with some precisions so we can move forward together for a quickfix.

Regards,
Georges

**Comment by brainfoolong** [comment]
Thanks for feedback. Yes i currently use memcache but i just want to get rid of that to require other external apps to run beside my simple php application. Therefore file caches are perfect for me. I started research and found PFC :)

In the past, file based cached didn't worked for me because of that write problem.
The big thing is that make this awkward, you may not notice any error during simultaneous write blocking each other. Just one thread wins and write the data to disk, the data from the other thread is lost without any notice because the write action works, but the data will be immediately overwritten by the other instance. This results in data loss. How big depends on how you use it.

The only way to get beyond this is some sort of using `flock`. In the past (few years ago) this worked really bad, than i switched to memcache. Now it is time for me to "reinvestigate" the issue. PFC is now here and possibly can manage this issue in nifty way.

I recommend to add tests and fixes for multiple (big) writes at same time. This makes this product even more reliable. I've done some tests and it seems that is not imun against that problem (writing a 3mb array to cache, on multiple php cli instances).

**Comment by brainfoolong** [comment]
Additionally, here is the test that i've written. Just run it in two cli windows simultaneously. One cli will stop reall fast with the die() error message

[test.php.txt](https://github.com/PHPSocialNetwork/phpfastcache/files/497972/test.php.txt)

**Comment by brainfoolong** [comment]
Also additionally i've tried myself to implement `flock`. It does not work, as it has doesn't worked years before :( (at least on windows). The lock never aquire. 

I guess a temporary mutex lock file and check for existance is required. Creating an empty file with same filename as the storage file plus an affix like `.mutex` or something, before the `fopen` call. Than check if file exist, if yes, it's locked. If the write is done and the file is closed with `fclose`, the mutex file can be deleted - The file is released.

Until the mutex file exist, the original file is write blocked and a loop should check and `usleep` to wait for the write access, at least some x tries, after x tries it can fail with return false.

It's dirty but i know the problems with file locks, there is no better cross-platform way for this, as far is i know.

Just an idea to push you to the right direction.

**Comment by Geolim4** [comment]
To be efficient the lock must be exclusive, but on some environment (E.g Unix) super-users can still open the file (like root). The Mutex is a bad idea, in case of an Exception is trowed or a fatal error occurs, the mutex stays on the disc which will lock the file forever.

I will work on a fix in the next days but this will be a modification that will must be enabled in options (E.g. secureFileManipulation) cuz this can decrease performances.

I will first release this on V6 which is still in development then merging to the V5 if everything looks good.

**Comment by brainfoolong** [comment]
Thx for feedback. If you can solve the problem i'm happy, doesn't matter how you can do it. For the mutex idea: Sure, additional checks will be required, for example if file is older than x seconds than it's obvious that something went wrong. A option to activate is, is a good idea.

**Comment by Geolim4** [comment]
My computer is too powerful (SSD mounted in Raid) :laughing: i have to pick a powerless one to make my test, could take me some day to find one.

**Comment by Geolim4** [comment]
@brainfoolong I got the concept i think:
https://github.com/PHPSocialNetwork/phpfastcache/blob/V6/src/phpFastCache/Drivers/Files/Driver.php#L92


Instead of writing directly the file, we write it in the directory with a temporary name, then once it's written completely we move it ti it's real name.

Looks fine to you ?

**Comment by Geolim4** [comment]
Please test the V6, if the tests look ok for you I'll make an unit test.

**Comment by Geolim4** [comment]
@brainfoolong Up :)

**Comment by brainfoolong** [comment]
@Geolim4 I answer from now in the dedicated issue/pull request for this. https://github.com/PHPSocialNetwork/phpfastcache/issues/366
