### ISSUE TITLE
Add secure file manipulation for disc-based drivers, see #365

### ISSUE THREAD

**Issue by Geolim4** [PHPSocialNetwork/phpfastcache#366]

**Comment by Geolim4** [comment]
Related to #365

**Comment by brainfoolong** [comment]
Hi, thx for implementation.
When i use `"secureFileManipulation" => true` in config, than i get these error messages `Warning: rename(,D:\phpfastcache-6.0.0-alpha\src\tmp\cli\files/2d/2d0aaa0b1e221f7990b8a82642f1580f.txt): Das System kann den angegebenen Pfad nicht finden. (code: 3) in D:\phpfastcache-6.0.0-alpha\src\phpFastCache\Core\Pool\DriverBaseTrait.php on line 121`.

With  `"secureFileManipulation" => false` all work as expected. Seems like file path's are incorrect.

**Comment by Geolim4** [comment]
Hi,

Can you translate me the german sentence please ? :)

Thanks you

**Comment by brainfoolong** [comment]
"System could not find the file at given path".

**Comment by Geolim4** [comment]
Ok thanks you, i will have a look

**Comment by Geolim4** [comment]
I fixed something wrong (realpath does not work on non-existing dir/files):

I made a test with a sleep on it and it seem to work very well:
![capture](https://cloud.githubusercontent.com/assets/1332071/19057006/2b5507b6-89cd-11e6-8afe-609174cf7777.PNG)

Let me know if it's working fine for you :)

**Comment by brainfoolong** [comment]
I tested again, now i have this error messages `Warning: rename(D:\phpfastcache-6.0.0-alpha\src\tmp\cli\files\2d\tmp_644512e4e6dfe8873f5343973da84dc8,D:\phpfastcache-6.0.0-alpha\src\tmp\cli\files/2d/2d0aaa0b1e221f7990b8a82642f1580f.txt): Access Denied (code: 5) in D:\phpfastcache-6.0.0-alpha\src\phpFastCache\Core\Pool\DriverBaseTrait.php on line 123`.

Rename over an existing file is not allowed on windows, i guess. So change the suggested line to 

    copy($tmpFilename, $file);
    unlink($tmpFilename);

Worked well for me. 

But, the initial error is still present. When i think about it, it's correct. Copy the file over the existing file is pretty much the same as writing it directly to this file. Both block the file for a short time.

Nevermind, i see that there is no real way to avoid that problem without file locks. And file locks don't work as expected in PHP. I think, i should change the point of view from my side. I should not use a file cache to hold data in it that is required to accumulate data over a period of time. A file cache should be only what it is called to be, a cache. 

I currently use a memcache system to accumulate high amount of data (About 20 requests/second) that write and read from that cache. I think, to replace that with a file cache, is a wrong attempt from my side. 

Sorry that i've waisted your time. PFC is great and will switch to it, but for my case, a file cache will not work.

Maybe you should mention it somewhere in the specs that the file cache is not save against multiple concurrent writes/reads.

Here is a working test that show you the problem. Put it in the `src` folder and run it with 2x with CLI, in 2 window.s Somewhere in between the cache file could not be read from disk because the file is blocked from another thread. This means the cache could not receive cache data and than the cache will be flushed.

![animation](https://cloud.githubusercontent.com/assets/1684236/19063954/505da38a-8a07-11e6-9be2-17f16dd7303a.gif)

[file-read-error.php.txt](https://github.com/PHPSocialNetwork/phpfastcache/files/507770/file-read-error.php.txt)

**Comment by Geolim4** [comment]
Indeed the Files driver is not really intended for intensive usage, but more for a regular usage to cache some data some times. In your case it's very specific because you tried to write multiple cache data in the very exact same time which is almost impossible to do without memory cache such as Redis or Memcache.

However i will keep the `secureFileManipulation` option because it provide a more reliable writing system for long writing-operation. Many software today use this mechanism to write in temporary file then rename to the expected filename. It's a bit slower but it's very more reliable.

For extreme case like you, i will suggest to upgrade their cache system to a NoDb/Memory cache system.

I'm not closing this issue, until i finish to update the wiki, the readme and the code commentaries.

Thanks you,
Georges

**Comment by brainfoolong** [comment]
Thank you for your help.

**Comment by Geolim4** [comment]
The secure file manipulation has been implemented, i will update the wiki and the roadmap.
Thanks you.
