### ISSUE TITLE
[Suggestion] Giving instances ID's

### ISSUE THREAD

**Issue by HACKHERS** [PHPSocialNetwork/phpfastcache#477]
Hello, I don't have detailed knowledge about the whole system but why don't we give instances ID's (optionally) so getting instances will be easier and faster than ever

Thanks,
Sarp

**Comment by Geolim4** [comment]
Hello, 

What are you talking about exactly ?

**Comment by HACKHERS** [comment]
Well, correct me if I'm wrong but currently when we use getInstance('driverName') It searches for current drivers with configuration. I'm suggesting that when we are creating drivers lets say 

`new Psr16Adapter($defaultDriver, $driverID, [/* Config array */]);`

and when getting a driver

`getInstance($driverID)`

This way there is no problem with getting drivers btw I still doesn't understand how we can create 2 file drivers and get them without knowing all the configuration they have. (For example file drive 1 path= /path1/, file drive 2 path = /path2/)

Reference: https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV5%5D-Why-calling-getInstance()-each-time-is-a-bad-practice-%3F

(One extra: In wiki page, there isn't information about all the configs easiest example is the path. It could be the only one that is missing but wanted to say that too https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-The-driver-options )

**Comment by Geolim4** [comment]
Internally PhpFastCache already make use of an instance ID based on the driver & config:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/CacheManager.php#L205

Currently I can't break the compatibility by adding a new param to Psr16Adapter class as PhpFastCache follows the semver specs.

However can see things on a different way:
- Adding a getter (only) **getInstanceId()** to ExtendedCacheItemPoolInterface which represents the current (unique) instance ID.
- Adding an option to $config to set the Instance ID instead of generating it automatically.
- Throwing an Exception if trying to setup an already existing instance ID
- Adding a getter to CacheManager: CacheManager::getInstanceById($id)

What do you think about that concept ?

--
This change would be targeted for 6.1.x and 7.0 to be semver compliant
The 6.1 will be in development until October and will fast forward the 6.0 bug-fixes/improvements.

**Comment by HACKHERS** [comment]
This could be great!

Thanks @Geolim4

**Comment by Geolim4** [comment]
Okay the roadmap has been updated. 
I'm closing this issue, you will be notified by this one when the card will change it's state:
https://github.com/PHPSocialNetwork/phpfastcache/projects/4#card-3472014

Cheers,
Georges

**Comment by Geolim4** [comment]
Will be done in V7 instead of 6.1 as planned initially.
V7 is planned to be out fo Summer 2018, see [timeline ](https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Global-support-timeline)

**Comment by Geolim4** [comment]
Hello @HACKHERS this feature is now testable on V7 if you want to.

Cheers,
Georges.L
