### ISSUE TITLE
Is there something like getAll() to retrieve all keys that have been set ?

### ISSUE THREAD

**Issue by hriziya** [PHPSocialNetwork/phpfastcache#494]
### Configuration:

PhpFastCache version: `6.0.2`
PHP version: ` 7 `
Operating system: ` Windows 10  `

#### Question:

>Is there something like **getAll**() to retrieve all the key-value that have been cached and currently active (I mean, did not expired) ?

**Comment by Geolim4** [comment]
Hello,

No, because currently not all drivers let us know how many keys are stored
in cache. But you can use tags to achieve something like this.

Cheers,
Georges

Le 10 juil. 2017 2:52 PM, "Hitesh Riziya" <notifications@github.com> a
écrit :

Configuration:

PhpFastCache version: 6.0.2
PHP version: 7
Operating system: Windows 10
Question:

Is there something like *getAll*() to retrieve all the key-value that have
been cached and currently active (I mean, did not expired) ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PHPSocialNetwork/phpfastcache/issues/494>, or mute the
thread

**Comment by Geolim4** [comment]
I wrote you a tutorial:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV5%CB%96%5D-Fetching-all-keys

Cheers,
Georges

**Comment by Geolim4** [comment]
Referencing #92
