### ISSUE TITLE
Directory::getAbsolutePath() returns incorrect path

### ISSUE THREAD

**Issue by mzdr** [PHPSocialNetwork/phpfastcache#580]
### Configuration:

PhpFastCache version: `6.1.1`
PHP version: `7.1.14`
Operating system: `Mac OS X 10.13.3 (17D47)`

#### Issue description:

Using `path` with `files` driver _always_ returns an absolute path. Steps to reproduce:

1. `composer require phpFastCache/phpFastCache`
2. `mkdir cache`
3. `chmod 777 cache`
4. `touch index.php`
5. Paste into `index.php`:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use phpFastCache\CacheManager;

CacheManager::getInstance('files', ['path' => './cache']);
```

Now if I open the index.php with my local webserver, I get an exception saying:

`Fatal error: Uncaught phpFastCache\Exceptions\phpFastCacheIOException: Path "/cache/Auto/Files" is not writable, please set a chmod 0777 or any writable permission and make sure to make use of an absolute path ! Additional information provided by error_get_last(): mkdir(): Permission denied`

This is because it tries to write to `/cache/…` instead of `./cache`. 

Is this on purpose? Becaue `phpFastCache/Util/Directory::getAbsolutePath()` shall return an absolute path but doesn’t consider the actual filesystem.

If relative paths are considered to be a bad pattern, would you mind to explain why?

Thanks!

**Comment by Geolim4** [comment]
Hello there !

This is a good question :)

This choice has been made on purpose mainly because of the possible chdir/getcwd differences between a WEB and CLI execution for a single application.

This can lead to a completely unexpected cache directory resolution, where on the contrary an absolute path ensures you that the cache directory value is trusted and let ne doubt about it's resolution.

The good practice is usually to build a path with a ROOT project constant.
Drupal is doing it with `DRUPAL_ROOT` as well as Symfony with `kernel.root_dir`

Cheers,
Georges.L

**Comment by mzdr** [comment]
Hi Georges!

Thanks for your fast feedback, really appreciate it. I totally get your point.

But wouldn‘t this be a mistake on the user side? For example it‘s generally recommended use `include/require` in combination with `__DIR__` because of the common pitfalls users are not aware of. But your input isn‘t altered in any way like in our scenario here.

I would prefer to have an expected output and rather warn/inform the user in the docs about the issues with relative paths than returning an incorrect output/path.

What do you think?

Best regards,
Sebastian

**Comment by Geolim4** [comment]
This behavior is already mentioned in the WIKI :)
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-The-driver-options#hostauthenticating-options-

> * **path** _| string (default: not set)_ `[>=V4], [>=V6.1]` The absolute path where the written cache files belong to (system temp directory by default). **As of the V6.1** this option is also used to define (P)redis and Memcache(d) UNIX socket

The output is _technically_ correct, the documentation reading belong to the end user/developer that will implement PFC on the project.

However if you think that this could be helpful, I can throw an error if a (guessed) relative directory is passed to the `$path` option :)

**Comment by mzdr** [comment]
I see. Can you give me an example for the “possible chdir/getcwd differences between a WEB and CLI execution for a single application” you were talking about? I’m still not convinced why you should enforce an absolute path, especially if it’s related to a specific set of conditions.

Let’s say I’m building a very simple web application and I have a single configuration file that will be shared among several other developers. Now how do I get around the problem of the absolute path? Sure you could say that I need some kind of setup routine, but this overhead would be introduced by your “restriction”.

Are you totally against loosing up this rule/restriction? I think it’s the users responsibility to take care of path differences/incompatibilities within a single application among different types of execution.

**Comment by Geolim4** [comment]
There's plenty examples if you look out on Google of chdir issues with CLI/WEB apps on php.

Also defining a sort of "root path" is not a big deal and is even a recommended practice since it allows you to define a trusted _base root dir_ that will represents your application root directory.

This kind of constant is absolutely implemented in all moderns (and old ones) php project:

- [Symfony](https://symfony.com/blog/new-in-symfony-3-3-a-simpler-way-to-get-the-project-root-directory)
- [Drupal](https://api.drupal.org/api/drupal/install.php/constant/DRUPAL_ROOT/7.x)
- [phpBB](https://github.com/phpbb/phpbb/blob/master/phpBB/index.php#L21)
- [Wordpress](https://codex.wordpress.org/Function_Reference/get_home_path)
- [Prestashop](https://github.com/PrestaShop/PrestaShop/blob/develop/config/defines.inc.php#L56)
- [Laravel](https://laravel.com/docs/5.6/helpers#paths)
- ...

Shall I continue ?

I'm not introducing a restriction at all, on the contrary I'm enforcing a best practice.

So no I won't change this behavior, like you said, "I think it’s the users responsibility to take care of path".

Asking them for an absolute path give 'em good practices and make their good safer.

Is that really a big deal to declare that simple statement in the top of the bootstrap of your code ?
```php
define('MY_APP_ROOT_PATH', __DIR__);
```

I don't really understand your issue with that, in fact it looks like you've been used (no offense) too much bad practices or just not enough good ones ?

**Comment by mzdr** [comment]
Hey Georges,

thanks a lot for your very detailed answer. Though I wasn’t asking for examples about using a consistent root path, but about the “possible chdir/getcwd differences between a WEB and CLI execution for a single application”.

Anyway. I still think it should be up to the developer if he wants to use "best practices" or not. If he doesn’t there might be a good reason for that, you’ll never know. Not everyone is using big frameworks and so on, and not everyone is having a situation where the "best practice" would fit.

I’m not saying that I have a problem with defining a root path, I’m having a problem with "patronizing" the developer.

Nevertheless you already mentioned that you are not willing to change this behaviour. That’s totally okay for me and I will accept that. 👍

**Comment by Geolim4** [comment]
Indeed, I did not intend to change this behaviour for now, but I'll may reconsider adding a warning to the user that pass a relative path in the future.
Maybe for the v7 :)

Thanks for your feedback, much appreciated !
Cheers,
Georges.L
