### ISSUE TITLE
Increase number of key with Redis

### ISSUE THREAD

**Issue by dutom007** [PHPSocialNetwork/phpfastcache#582]
### Configuration:

PhpFastCache version: ` 6.1 `
PHP version: `5. 6`
Operating system: `FreeBSD 10.3`

#### Issue description:

I use the library with redis. Everything work fine but I am surprise about the numbers of key in redis.
My cache can exceed 3 days and the key keep to increase.
![capture](https://user-images.githubusercontent.com/11500275/37203102-d47282a6-238c-11e8-8bb5-ec20a30e9598.PNG)

Thanks you for your help

**Comment by Geolim4** [comment]
Hello,

You may have to setup a lower expiration date.
Each cache item uses two redis keys (one for the data, the other for indexing the tags).
Just for curiosity, what are you caching and how do you implemented the cache ?

Also you may have over-cached data via a dynamic key ?

Cheers,
Georges

**Comment by Geolim4** [comment]
@dutom007 Bump :)

**Comment by dutom007** [comment]
Sorry, I will answer monday :p

**Comment by Geolim4** [comment]
Okay, thanks you, happy weekend !

**Comment by dutom007** [comment]
Hi Geolim4,

My cache does not exceed 72h.

![capture](https://user-images.githubusercontent.com/11500275/37276161-49a64eb2-25e1-11e8-8f75-1d94b5ae0ff2.PNG)

The key continue to increase.

I use the cache to keep some variable (listing producs, category, articles... by sort and filter).

However the redis system don't take more memory...

**Comment by Geolim4** [comment]
Hello,

First of all don't use ` is_null($all_pays_cached->get())` but `$all_pays_cached->isHit()`.
Globally, don't use `is_null()` but `$var !== null` :P
(This is faster since this a language construct and not a runtime function)

Now the problem:
I'm not really sure that it is a PFC issue, as you can see here:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Drivers/Redis/Driver.php#L80

I make use of `setex` command as documented in Redis:
https://redis.io/commands/setex

The problem is that your cache backend is "too much" dynamic, I'm guessing that `$cache_keyword` is a user data that could possibly be completely random ? (If it does this is a bit dangerous..)

Also I'm not sure that Redis is cleaning by itself expired items periodically, you may have need to configure a cron for that.

Cheers,
Georges

**Comment by dutom007** [comment]
Hin

Thanks for «is_null» trick, you are right ! I change every where.

`$cache_keyword` is not for user but filters/sorts and languages.

In my exemple : all_pays_page2_sort3_lang2 use for the page 2, the sort 3 (alpha) and french (2).

I'm sorry but I didn't understand  «setex» problem

**Comment by Geolim4** [comment]
This is simply not an issue that is PFC-related :)

You simply have too much combinations possible with $cache_keyword ;)

Also since Redis is NOT auto-cleaning the expired key by itself, there's your issue.

Just flush the cache periodically or setup a cron that will cleanup expired  Redis keys. 
(This is not to PFC to handle this kind of task).

Cheers,
Georges.

**Comment by dutom007** [comment]
Ok I understand.

Can you tell me the request to clean only expired key ?

**Comment by dutom007** [comment]
Hi Geolim,

I see on documentation : https://redis.io/commands/expire

> Set a timeout on key. After the timeout has expired, the key will automatically be deleted.

So the key would be deleted, no ?

**Comment by Geolim4** [comment]
Hello,

I'm doing the same thing:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Drivers/Redis/Driver.php#L80

I make use of `setex` command as documented in Redis:
https://redis.io/commands/setex

> Set key to hold the string value and set key to timeout after a given number of seconds. This command is equivalent to executing the following commands:
```
SET mykey value
EXPIRE mykey seconds
```

Cheers,
Georges
