### ISSUE TITLE
Any reason why not to use Memstatic in production?

### ISSUE THREAD

**Issue by Schlaefer** [PHPSocialNetwork/phpfastcache#583]
The memstatic driver is labeled as "Development" in the docs. Is there any reason to not use it if the the cache is only supposed to cache items for the current request?

**Comment by Geolim4** [comment]
Hello,

Good question indeed :)

Since this cache is a "Static memory" cache it is not really recommended to use it in production except for some specific context such as volatile data that should not be persisted at all but that should also not be fetched multiple time.

The decision to flag it as a "Production" driver was mainly to avoid beginners to use it in the wrong way and get their application performance even worse. 

However if you want use it in a specific way and you know the consequences/advantages/cons of a "Static memory" cache, feel free to implement it in your code 😸 

Cheers,
Georges.

**Comment by Schlaefer** [comment]
Thanks. Just asked to be sure. 👍
