### ISSUE TITLE
Will/can the lib retry to write/read ?

### ISSUE THREAD

**Issue by Yamakasi** [PHPSocialNetwork/phpfastcache#631]
I was wondering if the lib will try to read or write again when it fails or it's application wise to manage that. Maybe an option with false for not, 0 for unlimited and 1 - .... 99 for the retries you want to do before exit with fail ?

**Comment by Geolim4** [comment]
Hello,

Errors are something serious enough to handle them yourself using a try/catch bloc.
The library is already having a fallback on initialization if the cache backend is failing for some reason (missing extension, unreachable server, etc).

So no, the library won't handle retry attempts because this would make the code unmaintainable and also because it's against KISS principle.

Cheers,
Georges.

**Comment by Yamakasi** [comment]
Yes I see the fallback function. It was more a question do I don't create functions that will be in (later).

I don't think a try/catch is always a proper way and can get too many exceptions following up.
