### ISSUE TITLE
What happens with Tags(index) on update/set item again

### ISSUE THREAD

**Issue by Yamakasi** [PHPSocialNetwork/phpfastcache#638]
When I have a document in cache and I want to update it's content, will the tags stay in the tagindex and is this managed by the wrapper or do I need some extra steps.

As the data (in Couchbase) is binary I cannot check my backend that easy for what's in there. (is there some debug function for this so we can see what is in the backend exactly ?)

**Comment by Geolim4** [comment]
Hello,

The tags stay as long as the cache item is not expired.
You can see that behavior you the /tests directory.

Cheers,
Georges

**Comment by Yamakasi** [comment]
But they also exist when you add the item again with the same Id, so you overwrite it ? The expire is re(set) then again so I was wondering how that should behave.

**Comment by Geolim4** [comment]
They're attached again to their items.
I'll try to draw you something when coming home.

**Comment by Yamakasi** [comment]
Sounds great! I can make a list if you want and ask why what functions give back what and why we check for it, like isHit() is the same as you check is the call gives data back or is empty... I use it but don't see a direct usecase where it would add something extra. 

Maybe it's a good idea as addition next to the API explanation we can add ?

For the rest it's awesome this lib, good work! ;)

**Comment by Geolim4** [comment]
To answer to your question about tags behavior, here's is a (simplified) schema of how it's working:

![image](https://user-images.githubusercontent.com/1332071/43168685-7c5b216c-8f9e-11e8-94bf-744195eee1da.png)

- Each tag is in fact a **private (not directly accessible) tag cache item ** by itself that reference each **real** cache item (as a an array of cache keys) that make use it.
  - Each **private tag cache item** that represent a tag has an expiration date of the biggest cache item TTL that it contains.
- Each cache item contain a list (as an array) of the used tags.
  - Each cache item removed will be also removed of the index of the **private tag cache item**
    - If the **private tag cache item** reference no more valid cache item it will also be removed to prevent dangerous memory leak in cache backend.

Finally, `isHit()` call is about race condition because it does not return the whole data that will be compared later against `empty` or `isset`.

Hope I answered your questions.

**Comment by Yamakasi** [comment]
Great drawing and design and explanation! Thanks a lot!

About is isHit(); I understand, if you know you have a document but also can empty it from time to time you can better check it's status, empty OR data AND existing. Am I right ?
