### ISSUE TITLE
Improve the doc of Pool concept and detach method

### ISSUE THREAD

**Issue by floSoX** [PHPSocialNetwork/phpfastcache#687]
**Configuration**
- **PhpFastCache version:** 7.0.5
- **PhpFastCache API version:** 2.0.4
- **PHP version:** `PHP 7.1.27-1+0~20190307202204.14+stretch~1.gbp7163d5 (cli) (built: Mar  7 2019 20:22:04) ( NTS )`
- **Operating system:** Debian Stretch

**Is your feature request related to a problem? Please describe.**
When you use PhpFastCache in a loop, it's not easy to know that you have to use the `detach` method to force it to get the cache value.

**Describe the solution you'd like**
Improve the doc of Pool concept and detach method to describe the default behaviour and to highlight the `detach` method.

**Additional context**
https://stackoverflow.com/questions/46074121/missing-cache-items-via-phpfastcache-using-server-side-events

**Comment by Geolim4** [comment]
Hello, this is not really an issue since the cache item are statically stored (more like cached in fact) in the cache backend until it's released using detachItem() or using cacheClear(). This has been made in order to improve the library performances since Phpfastcache is mainly used in a web context and more rarely used in a "loop context" such as a cron task or perpetual CLI script.

However I agree with you that this kind of implementation deserves a specific documentation, maybe in the Wiki.

**Comment by Geolim4** [comment]
Here ya go:

https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV5%CB%96%5D-Detaching-Attaching-item-to-from-pool

**Comment by Geolim4** [comment]
Thanks for your contributions ;)

**Comment by floSoX** [comment]
Yay!
Thanks for this new doc :-)
