### ISSUE TITLE
Redis lock for a record, SETNX feature

### ISSUE THREAD

**Issue by ethereal-sandeep** [PHPSocialNetwork/phpfastcache#696]
How can i do SETNX in phpfastcache

**Comment by Geolim4** [comment]
Hello,

This "feature" is not a part of "[psr16](https://www.php-fig.org/psr/psr-16/)" standards.
It's Redis specific and therefore has no place in PFC.

You have to implement your own logic on this.
Cheers,
Georges.

**Comment by ethereal-sandeep** [comment]
is there a way to run native redis command via phpfastcache api?

**Comment by Geolim4** [comment]
But why ?
This is not the purpose of the "caching practice" nor PSR16 specs.

**Comment by ethereal-sandeep** [comment]
so i want to develop a lock system for a key in redis cache. In redis-cli i am able to achieve this with setnx but with phpfastcache lib i am unable to do this. Can you suggest something

**Comment by gamort** [comment]
@ethereal-sandeep 

A very brief overview of the documentation shows that locking already exists, see Dealing With cache slams, https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV6%CB%96%5D-Dealing-with-cache-slams . I do not personally LIKE that solution, traditional placeholder locking is to create a SECOND file/key value based on the first, such as for MyKey create .__MyKey and store the PID in that key.  If the lock key exists, check to make sure the PID is still executing.

Soo,  If that is insufficient/unpalatable for you as well, instead of writing locking mechanisms, simply use SETNX extending the Redis driver class:

For the basics see:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV5%CB%96%5D-Extending-phpFastCache

https://github.com/PHPSocialNetwork/phpfastcache/blob/master/lib/Phpfastcache/Drivers/Redis/Driver.php 

Make your own class, example RedisNx
Use setnx instead of setex in DriverWrite

To avoid duplicate connections if you also want to use the regular set then you create 2 pools, one using Redis and one using RedisNx
Grab the Redis client from your Redis pool, and then pass it to RedisNx - see driverConnect
