### ISSUE TITLE
How to setup a memcached cluster with fallback in case not supported?

### ISSUE THREAD

**Issue by andreapernici** [PHPSocialNetwork/phpfastcache#728]
**Configuration (optional)**
- **PhpFastCache version:** "last version"
- **PhpFastCache API version:** "last version"
- **PHP version:** "php 7.3"
- **Operating system:** " linux "

**My question**
> Where I can find documentation on how to setup a Memcached cluster with apc fallback and the files fallback.

My stack is

If MEMCACHED -> GO USE IT with a 2 node cluster (how to setup the cluster?)
else if APC -> GO USE IT
else FILES

From what I read PhpFastCache is already supporting fallback, but I can't find this kind of documentation.

I also saw this https://github.com/PHPSocialNetwork/phpfastcache/blob/master/lib/Phpfastcache/Cluster/AggregatorInterface.php
but it's not clear to me how to setup a cluster replication setup.

Thanks.

**Comment by andreapernici** [comment]
Up to now I figured out using a try catch, but I don't think it's the proper way to do that.

**Comment by Geolim4** [comment]
Hello, 

Simply look at `lib/Phpfastcache/Drivers/Memcached/Config.php` or `lib/Phpfastcache/Drivers/Memcache/Config.php`.

Don't rely on fallback for now because it's been removed in v8:
> https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV5%CB%96%5D-Configuring-a-fallback-driver

Also:
PhpFastCache version: "last version"
PhpFastCache API version: "last version"

No it's not. The v8 has been released couple of day ago.
So please specify the version. From a version to another, things change and I'm not aware at all of which version you're using.

Thanks
Georges

**Comment by andreapernici** [comment]
In my composer I have

```
        "phpfastcache/phpfastcache": "^7.1",
        "ext-apcu": "^5.1",
        "cache/memcached-adapter": "^1.0"
```

**Comment by Geolim4** [comment]
> Honestly here I can't see any documentation on the setup

https://github.com/PHPSocialNetwork/phpfastcache/blob/707803e7c42a3612b42ca8c1b9bb14cf657f1655/lib/Phpfastcache/Drivers/Memcache/Config.php#L28

**Comment by Geolim4** [comment]
Hello @andreapernici ,

I’m closing this issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L
