### ISSUE TITLE
can't set securityKey on Psr16Adapter

### ISSUE THREAD

**Issue by sir-reynolds** [PHPSocialNetwork/phpfastcache#741]
**Configuration (optional)**
- **PhpFastCache version:** 7.1.1
- **PhpFastCache API version:** 2.0.4
- **PHP version:** php 7.2
- **Operating system:** ubuntu 16.04

**My question**
> i want to set path location and securityKey on Psr16Adapter .
i already try :
require_once 'vendor/autoload.php';
use Phpfastcache\Helper\Psr16Adapter;
$Psr16Adapter = new Psr16Adapter('sqlite', ['path'=> '/var/www/html/_tmp_cache_', 'securityKey' => 'custom_key']);

thats config always error, but when i set path only success.

**Comment by Geolim4** [comment]
Hello,

What's the error ?

**Comment by sir-reynolds** [comment]
[Wed Jun 17 20:43:41.996042 2020] [php7:error] [pid 30464] [client 127.0.0.1:52894] PHP Fatal error:  Uncaught Phpfastcache\\Exceptions\\PhpfastcacheInvalidConfigurationException: Invalid option(s) for the config Phpfastcache\\Config\\ConfigurationOption: securityKey in /var/www/html/webStore/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Config/ConfigurationOption.php:113\nStack trace:\n#0 /var/www/html/webStore/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/CacheManager.php(582): Phpfastcache\\Config\\ConfigurationOption->__construct(Array)\n#1 /var/www/html/webStore/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/CacheManager.php(115): Phpfastcache\\CacheManager::validateConfig(Array)\n#2 /var/www/html/webStore/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Helper/Psr16Adapter.php(52): Phpfastcache\\CacheManager::getInstance('sqlite', Array)\n#3 /var/www/html/webStore/index.php(34): Phpfastcache\\Helper\\Psr16Adapter->__construct('sqlite', Array)\n#4 {main}\n  thrown in /var/www/html/webStore/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Config/ConfigurationOption.php on line 113

**Comment by Geolim4** [comment]
Did you tried to search the issue in Github 🙄 ?

Because I already explicated that error and it's documented in Wiki:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Configuration-Options

This config option does not belong to a global config option  object (aka array) but to a specific config option:
https://github.com/PHPSocialNetwork/phpfastcache/issues/723#issuecomment-594781628

In your case use the "Files" option config, not the Sqlite one.
Cheers,
Georges
