### ISSUE TITLE
New Release 2.4.2 on Feb 09 & Next Release 3.1.0 on April 12

### ISSUE THREAD

**Issue by khoaofgod** [PHPSocialNetwork/phpfastcache#78]
- Feb 09 / What's new?
+ predis supported.
+ improved files driver.
+ improved sqlite
+ improved redis: supported database select
+ improved base config.
+ improved composer

Next release will be on April 12
+ tags keywords
+ search keywords
+ global statstic

**Comment by reno1979** [comment]
Yeah! 
Search and tags!

**Comment by khoaofgod** [comment]
working & scheduled, search & tags.
LMAO, now I feel it like a Universial NoSQL Database now with non-expired caching time + tags + search.

**Comment by reno1979** [comment]
How will search work? 
I mean will php fastcache maintain an array which keys represent the stored data? 
So you can search very fast because it does an isset..?

That brings me to an other question, I try to retrieve data from cache but when empty I generate the data and store it. Is it faster to first  try $cache->isExisting("keyword");??

**Comment by khoaofgod** [comment]
I will be gone until April 12.
I have a filming project for Christian TV program, and I have to finish it for them on Easter, April.
So, until now, I will only fix small bugs, the next release will be moved to April 12.

**Comment by khoaofgod** [comment]
I movie project is still not finished yet, I will delay this one a little bit longer by end of this month.

**Comment by reno1979** [comment]
Any updates about your progress?

**Comment by triune** [comment]
Yeah, what happened to 3.x ??
