### ISSUE TITLE
secureFileManipulation clarification about path option

### ISSUE THREAD

**Issue by DePalmo** [PHPSocialNetwork/phpfastcache#785]
**Configuration**
- **PhpFastCache version:** "7.0.5"
- **PhpFastCache API version:** "2.0.4"
- **PHP version:** "7.4"
- **Operating system:** "Windows 10 Pro and Linux com-linssh037 5.4.78-combell #202011181941 SMP Wed Nov 18 19:41:39 UTC 2020 x86_64 GNU/Linux"

**My question**
I init the library like this:
```
try {
	CacheManager::setDefaultConfig(new Config([
		"path" => dir_root . '_cache',
		"itemDetailedDate" => false,
		"secureFileManipulation" => true
	]));
} catch (PhpfastcacheInvalidConfigurationException $e) {
} catch (ReflectionException $e) {
}
$cache = new Psr16Adapter('Files');
```
Then use it like this:
```
$translation = $this->cache->get('translation');
$this->cache->set('translation', $translation);
```
Up until I started using `secureFileManipulation`, I always saw a folder `_cache` being created and used, but when I set `secureFileManipulation` to `true`, that folder is not being created and I can't find cached files. I tested the caching code and it appears working, but the website feels a bit slower than before. Please note that I am caching some strings and my code would call database multiple times, so with your caching library, this was speed up by a lot.

So my question is: is it normal that I do not see `_cache` folder being created and used, when I am using `secureFileManipulation`? If yes, when are the files then stored?

**Comment by Geolim4** [comment]
Yeah,

This option will make advanced file verification before writing the file on the disk, this is usually enabled when there's a high conflict risk due to an intense I/O activity.

Except if you think that there's a risk of failing filesystem this option is not very useful.

It use a mechanism of "temporary name then write and rename" instead of "direct file write".

So this behavior is totally normal and you may furtively notice a sub-folder called "tmp_xxxxxxxxxxx" during write operations.

Cheers,
Georges

**Comment by DePalmo** [comment]
Thank you for your response. The problem is that after the code executes without any issues, there's no `_cache` folder at all. It's not being created and no `tmp_` folder is there either.

**Comment by Geolim4** [comment]
The tmp_ file (sorry) is only created during script execution then immediately renamed to its true name.

This is why this can slow down a bit your website.
