### ISSUE TITLE
Getting Exception in Phpfastcache

### ISSUE THREAD

**Issue by prakashmuvi** [PHPSocialNetwork/phpfastcache#786]
**Configuration**
- **PhpFastCache version:** "7.1.0"
- **PhpFastCache API version:** "v7"
- **PHP version:**".7.0.33."
- **Operating system:**"Linux"
**Describe the bug**

> ... Path "/var/www/vhosts/muvi-usa/cache/48397/language/api.muvi.com/Files/46/d6" is not writable, please set a chmod 0777 or any writable permission and make sure to make use of an absolute path ! Additional information provided by error_get_last(): mkdir(): File exists in /var/www/vhosts/muvi-usa/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Core/Pool/IO/IOHelperTrait.php line 165 ...

**To Reproduce**
Steps to reproduce the behaviour:
We are getting this type of exception randomly for multilingual website. We have set the file and folder permission 0777

**Expected behaviour**
It should not raise the above type of exception.

We are getting this exception randomly. Last 2 days not getting any exception. Previously, we had changed the cache folder size and not getting this exception but today we got an exception.

**Comment by Geolim4** [comment]
And I'll repeat you this answer:
https://github.com/PHPSocialNetwork/phpfastcache/issues/783#issuecomment-769776887

> ```php
>         if (!$skip && !\is_dir($path) && @!\mkdir($path, $this->getDefaultChmod(), true) && !\is_dir($path)) {
>            throw new PhpfastcacheIOException('Path "' . $path . '" is not writable, please set a chmod 0777 or any writable > permission and make sure to make use of an absolute path !');
>         }
> ```
> See ? I can't change that, this is an issue with your filesystem, not Phpfastcache.
> The above code does the following things:
>
> - Checking if $skip isn't true
> - Checking if directory exists
> - Attempting to create it, recursively if needed
> - Check if the directory created effectively exists
>
> If everything above return false it means that the directory does not exists and have not created leading to an exception.

The code above works as designed and strong tests are showing that this driver is not getting any exception even under intense I/O activity.

Sorry but it's not Phpfastcache's fault.

**Comment by AntiEngineer** [comment]
@prakashmuvi Hello there.

As Geolim stated above, it's a misconfiguration on your side rather than an issue with Phpfastcache.

I've tried the following and it fails on certain cases, such as symlinks and such. 
These also depend on your input and the way you're attempting to store to cache, considering using a different storage driver if you can't solve the problem with your current configuration.

I don't find the reason this issue should be open.

**Comment by prakashmuvi** [comment]
Hi Support,
Thanks for your reply.
We have used this library for more than 3 years.
We are getting this exception randomly. Particularly when traffic is very high. Could you please suggest where to set $skip= false. 
We are just providing the parent folder as the path but this library will create child folder and files internally. 

Could you please suggest how to resolve this issue? We have tried multiple times to reproduce this issue in our staging environent but not successfully. 
Do you have any suggestion ?

**Comment by Geolim4** [comment]
>  We are getting this exception randomly. Particularly when traffic is very high. Could you please suggest where to set $skip= false.

This variable is an internal variable which is not usable on your side.

> We are getting this exception randomly. Particularly when traffic is very high. 

Then I think that your disk may be in a overload situation and cannot manage all this I/O operation correctly.

You are may facing a race condition and I suggest you to migrate to a strongest driver such as Redis, Memcache, etc.

Like I said again, after deep investigation and strong unit tests, the issue is NOT on Phpfastcache side but mostly on your server implementation.
